language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
    - ./install_dependencies.sh
script:
    - PATH=/home/travis/bin:$PATH cargo test
    - PATH=/home/travis/bin:$PATH cargo build --manifest-path example/Cargo.toml
